Update Test.yml

diff --git a/.github/workflows/Test.yml b/.github/workflows/Test.yml
--- a/.github/workflows/Test.yml
+++ b/.github/workflows/Test.yml
@@ -25,6 +25,31 @@ jobs:
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt
+      - name: Validate environment variables
+        run: |
+          required_vars=(
+            TELEGRAM_BOT_TOKEN
+            TELEGRAM_CHAT_ID
+            OPENWEATHERMAP_API_KEY
+            LASTFM_API_KEY
+            LASTFM_API_SECRET
+            SPOTIFY_CLIENT_ID
+            SPOTIFY_CLIENT_SECRET
+          )
+          for var in "${required_vars[@]}"; do
+            if [ -z "${!var}" ]; then
+              echo "Error: $var is not set."
+              exit 1
+            fi
+          done
       - name: Run test script
+        env:
+          TELEGRAM_BOT_TOKEN: ${{ vars.TELEGRAM_BOT_TOKEN }}
+          TELEGRAM_CHAT_ID: ${{ vars.TELEGRAM_CHAT_ID }}
+          OPENWEATHERMAP_API_KEY: ${{ vars.OPENWEATHERMAP_API_KEY }}
+          LASTFM_API_KEY: ${{ vars.LASTFM_API_KEY }}
+          LASTFM_API_SECRET: ${{ vars.LASTFM_API_SECRET }}
+          SPOTIFY_CLIENT_ID: ${{ vars.SPOTIFY_CLIENT_ID }}
+          SPOTIFY_CLIENT_SECRET: ${{ vars.SPOTIFY_CLIENT_SECRET }}
         run: |
           python test_script.py || exit 0
